### ISSUE TITLE
Question: Reproducing BART 0.4B performance on WiT task

### ISSUE THREAD

**Issue by arjunbansal** [andreamad8/FSB#1]
Should running the following notebook:
`https://github.com/andreamad8/FSB/blob/main/retrievers/ParlAI_SearchEngine/colab.ipynb`

with the following search server config:
`python search_server.py serve --host $HOST --search_engine="Bing" --use_description_only --subscription_key "YOUR_KEY"`

and the following model:
`python -m parlai interactive --model-file zoo:sea/bart_fid_sqse/model --search_server $HOST --search-query-generator-model-file zoo:sea/bart_sq_gen/model`

...give the equivalent published performance from the paper for BART 0.4B (Table 5: F1=25.4, KF1=23.1, P=10.6)? Or are there some additional steps or configuration settings needed to match the published performance?

Thanks!

**Comment by andreamad8** [comment]
Hi, 

in FSB, we just used the retriever for the demo. Please, check: 
```
https://github.com/JulesGM/ParlAI_SearchEngine
```
for more details.
