### ISSUE TITLE
How to feed Custom domain related data

### ISSUE THREAD

**Issue by rbhatia46** [andreamad8/FSB#3]
Hi,
Great work on the Few shot bot, I have one basic question, how to feed custom domain related data/prompts to this architecture so that it can answer that domain related questions too? Any light on this would be very helpful. Thanks again,

Regards,
Rahul

**Comment by andreamad8** [comment]
Hi @rbhatia46 

Thanks for reaching out. 

You can add a new prompt template in this folder:
```
https://github.com/andreamad8/FSB/tree/main/prompts
```
and a object like this in the main:
```
          "persona": {"shot_converter":convert_sample_to_shot_persona, 
                    "shot_converter_inference": convert_sample_to_shot_persona,
                     "file_data":"data/persona/","with_knowledge":None,
                     "shots":{1024:[0,1,2],2048:[0,1,5]},"shot_separator":"\n\n",
                     "meta_type":"all","gen_len":50,"max_number_turns":5},
``` 
this means to include your data in the folder (e.g.,  "file_data":"data/persona/).

Let me know if this helps. I am a bit busy for a couple of weeks, but I can try to help if needed 

-- Andrea

**Comment by rbhatia46** [comment]
Thanks a lot for the prompt response, after doing this, any additional steps which are required to re-train?(sorry for the basic question, still going through your paper, just wanted to check the demo first), or can I simply run `streamlit run app.py` after adding my data as you mentioned.

**Comment by andreamad8** [comment]
no training involved here :) 

so yes you can just run app.py with a LM API of any kind, and it should work. I haven't done an integration with OpenAI but it's should be fairly simple. 

-- Andrea

**Comment by rbhatia46** [comment]
Understood, will give this a shot, thanks a lot again for your great work and for your help :)
